### ISSUE TITLE
CSS background img path error 

### ISSUE THREAD

**Issue by lslvxy** [codebandits/react-app-rewire-css-modules#6]
```
  .money {
        background: url(./money_vline.png) repeat-y;
|
```
error message
`Module not found: Can't resolve 'money_vline.png' in '/Users/xxx/WorkSpace/antd-demo/src/component/Money'`

it seem like lost a '/' 

if i set 
```
  .money {
        background: url(../Money/money_vline.png) repeat-y;
|
```
it works

**Comment by lnhrdt** [comment]
Closing this issue and archiving this project in favor of Create React App's [native support for CSS Modules](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet) introduced in v2.
